### ISSUE TITLE
Can support 1.11.2??

### ISSUE THREAD

**Issue by Jackytsang113** [smartin1018/martophsmedals#1]
[20:42:02] [Server thread/ERROR]: [MartophsMedals] Could not find support for this server version.
[20:42:02] [Server thread/ERROR]: Error occurred while enabling MartophsMedals v1.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
	at com.martoph.martophsmedals.MartophsMedals.onDisable(MartophsMedals.java:113) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at com.martoph.martophsmedals.MartophsMedals.onEnable(MartophsMedals.java:62) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Unknown Source)

**Comment by smartin1018** [comment]
Currently no support for 1.11.2. I plan to add this very soon.

**Comment by smartin1018** [comment]
Can you please paste what version spigot runs with /version?

**Comment by smartin1018** [comment]
Solved

**Comment by Jackytsang113** [comment]
Thank you very much
